server:
  port: 10010
spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors: # 全局的跨域处理
        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
        corsConfigurations:
          '[/**]':
            allowedOrigins: # 允许哪些网站的跨域请求
              - http://localhost:9001
              - http://localhost:9002
              - http://127.0.0.1:9001
              - http://127.0.0.1:9002
            allowedMethods: # 允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
            maxAge: 360000 # 这次跨域检测的有效期

      routes:
        - id: item-service
          uri: lb://item-service
          predicates:
            - Path=/item/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**, /pay/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**, /address/**
        - id: search-service
          uri: lb://search-service
          predicates:
            - Path=/search/**

    nacos:
      server-addr: 127.0.0.1:8848
