FROM elasticsearch:7.12.1

COPY ./elasticsearch-analysis-ik-7.12.1 /usr/share/elasticsearch/plugins/elasticsearch-analysis-ik-7.12.1
COPY ./elasticsearch-analysis-pinyin-7.12.1 /usr/share/elasticsearch/plugins/elasticsearch-analysis-pinyin-7.12.1

EXPOSE 9200
EXPOSE 9300